version: "3.7"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./conf:/etc/nginx/conf.d
    links:
      - php
      - db
    depends_on:
      - db
  php:
    build: .
    volumes:
      - ./code:/code
      - ./vendor:/vendor
      - ./.env:/.env
  db:
    image: mysql:latest
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
